workspace:
  ckpts_folder: 'ckpts'
  logs_folder: 'logs'
  epoch_prefix: 'e'
  ckpts_extension: '.pt'
  step_key: 'step'

base:
  data.noise: 0.0
  data.bdry_info_path: data/boundary_info_64x64.npz
  data.gn_path: data/cir3_64x64_c8/gn.npy
  data.gd_path: data/cir3_64x64_c8/gd/10653.npy
  data.label_path: data/cir3_64x64_c8/inclusion/10653.npz
  data.num_samples: 20480
  data.area: 4.0
  data.perimeter: 8.0
  u.sigma:
    - tanh
    - tanh
    - sinc
    - softplus
    - sinc
    - softplus
    - sinc
    - softplus
    - none
  u.dims: [20, 20, 20, 20, 20, 20, 20, 20, 1]
  gamma.sigma:
    - tanh
    - tanh
    - elu
    - tanh
    - elu
    - tanh
    - sigmoid
    - sigmoid
    - elu
  gamma.dims: [20, 20, 20, 20, 20, 20, 20, 20, 1]
  phi.sigma:
    - tanh
    - tanh
    - sinc
    - sinc
    - sinc
    - sinc
    - sinc
    - sinc
    - none
  phi.dims: [20, 20, 20, 20, 20, 20, 20, 20, 1]
  sgd1.lr: 0.010
  sgd1.weight_decay: 0.0000001
  sgd2.lr: 0.008
  sgd2.weight_decay: 0.0000001
  optim.jn: 2
  loss.coef_A: 0.0001
  loss.coef_AG: 0.001
  loss.coef_AP: 0.001
  loss.coef_B1: 1.0
  loss.coef_B2: 1.0
  loss.coef_B3: 1.0
  loss.coef_BP: 1.0
  phi_constraint: 200
  epochs: 20000

base/alpha:
  data.bdry_info_path: data/boundary_info_64x64.npz
  data.gn_path: data/cir3_64x64_c8_s26710/gn.npy
  data.gd_path: data/cir3_64x64_c8_s26710/gd/10653.npy
  data.label_path: data/cir3_64x64_c8_s26710/inclusion/10653.npz
  data.num_samples: 40000


simple:
  data.noise: 0.0
  data.bdry_info_path: data/boundary_info_64x64.npz
  data.gn_path: data/cir3_64x64_c8/gn.npy
  data.gd_path: data/cir3_64x64_c8/gd/10653.npy
  data.label_path: data/cir3_64x64_c8/inclusion/10653.npz
  data.num_samples: 20480
  data.area: 4.0
  data.perimeter: 8.0
  u.sigma:
    - tanh
    - tanh
    - sinc
    - softplus
    - none
  u.dims: [128, 64, 32, 16, 1]
  gamma.sigma:
    - tanh
    - tanh
    - elu
    - tanh
    - elu
  gamma.dims: [128, 64, 32, 16, 1]
  phi.sigma:
    - tanh
    - tanh
    - sinc
    - sinc
    - none
  phi.dims: [128, 64, 32, 16, 1]
  sgd1.lr: 0.010
  sgd1.weight_decay: 0.0000001
  sgd2.lr: 0.008
  sgd2.weight_decay: 0.0000001
  optim.jn: 2
  loss.coef_A: 0.0001
  loss.coef_AG: 0.001
  loss.coef_AP: 0.001
  loss.coef_B1: 1.0
  loss.coef_B2: 1.0
  loss.coef_B3: 1.0
  loss.coef_BP: 1.0
  phi_constraint: 200
  epochs: 20000


simple/test1:
  loss.coef_AP: 0.01


simple/wide1:
  u.dims: [256, 128, 64, 32, 1]
  gamma.dims: [256, 128, 64, 32, 1]
  phi.dims: [256, 128, 64, 32, 1]


simple/alpha:
  data.bdry_info_path: data/boundary_info_64x64.npz
  data.gn_path: data/cir3_64x64_c8_s26710/gn.npy
  data.gd_path: data/cir3_64x64_c8_s26710/gd/10653.npy
  data.label_path: data/cir3_64x64_c8_s26710/inclusion/10653.npz
  data.num_samples: 40000