
data:
  train_set_location: "lafem/data/cir3_e64_64_c8/"
  train_set_start: 0
  train_set_end: 900
  train_batch_size: 10

  validate_set_location: "lafem/data/cir3_e64_64_c8/"
  validate_set_start: 900
  validate_set_end: 1000
  validate_batch_size: 10


iter_head: 0
epochs: 50

lr: 0.001
weight_decay: 0.000000001
momentum: 0.9

log_dir: "lafem/logs/"
save: True
checkpoint_dir: "lafem/ckpts/"


defaults:
  blank: None


task1:
  noise: 0.0
  use_noise_filter: False
  tag: 'nn_multi'
  type_: 'multi'


task2:
  noise: 0.0
  use_noise_filter: False
  tag: 'nn_single'
  type_: 'single'


task3:
  noise: 0.0
  use_noise_filter: False
  tag: 'nn_nograd'
  type_: 'nograd'


task4:
  noise: 0.01
  use_noise_filter: False
  tag: 'gn01_multi'
  type_: 'multi'


task5:
  noise: 0.01
  use_noise_filter: False
  tag: 'gn01_single'
  type_: 'single'


task6:
  noise: 0.01
  use_noise_filter: False
  tag: 'gn01_nograd'
  type_: 'nograd'


task7:
  noise: 0.05
  use_noise_filter: False
  tag: 'gn05_multi'
  type_: 'multi'


task8:
  noise: 0.05
  use_noise_filter: False
  tag: 'gn05_single'
  type_: 'single'


task9:
  noise: 0.05
  use_noise_filter: False
  tag: 'gn05_nograd'
  type_: 'nograd'


task10:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_multi'
  type_: 'multi'


task11:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_single'
  type_: 'single'


task12:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_nograd'
  type_: 'nograd'


task13:
  noise: 0.42
  use_noise_filter: True
  tag: 'ln05_multi'
  type_: 'multi'


task14:
  noise: 0.42
  use_noise_filter: True
  tag: 'ln05_single'
  type_: 'single'


task15:
  noise: 0.42
  use_noise_filter: True
  tag: 'ln05_nograd'
  type_: 'nograd'


argpools:
  gpu_id: [0,]


pool_size: 4
