
data:
  train_set_location: "data/cir3_64x64_c8_s26710/"
  train_set_start: 0
  train_set_end: 10000
  train_batch_size: 500

  validate_set_location: "data/cir3_64x64_c8_s26710/"
  validate_set_start: 10000
  validate_set_end: 12000
  validate_batch_size: 500


iter_head: 0
epochs: 1500

lr: 0.001
weight_decay: 0.000000001
momentum: 0.9

log_dir: "num_pairs/logs/"
save: True
checkpoint_dir: "num_pairs/ckpts/"


defaults:
  blank: None


task1:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_multi'
  type_: 'multi'
  n_channel: 1

task2:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_single'
  type_: 'single'
  n_channel: 1

task3:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_nograd'
  type_: 'nograd'
  n_channel: 1

task4:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_multi'
  type_: 'multi'
  n_channel: 2

task5:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_single'
  type_: 'single'
  n_channel: 2

task6:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_nograd'
  type_: 'nograd'
  n_channel: 2

task7:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_multi'
  type_: 'multi'
  n_channel: 3

task8:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_single'
  type_: 'single'
  n_channel: 3

task9:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_nograd'
  type_: 'nograd'
  n_channel: 3

task10:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_multi'
  type_: 'multi'
  n_channel: 4

task11:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_single'
  type_: 'single'
  n_channel: 4

task12:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_nograd'
  type_: 'nograd'
  n_channel: 4


task13:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_multi'
  type_: 'multi'
  n_channel: 5

task14:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_single'
  type_: 'single'
  n_channel: 5

task15:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_nograd'
  type_: 'nograd'
  n_channel: 5


task16:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_multi'
  type_: 'multi'
  n_channel: 6

task17:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_single'
  type_: 'single'
  n_channel: 6

task18:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_nograd'
  type_: 'nograd'
  n_channel: 6


task19:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_multi'
  type_: 'multi'
  n_channel: 7

task20:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_single'
  type_: 'single'
  n_channel: 7

task21:
  noise: 0.084
  use_noise_filter: True
  tag: 'ln01_nograd'
  type_: 'nograd'
  n_channel: 7


argpools:
  gpu_id: [0, 1, 2, 3]


pool_size: 4
