
data:
  train_set_location: "./data/gdgn_64_64_train/"
  train_set_volume: 10000
  train_batch_size: 500
  validate_set_location: "./data/gdgn_64_64_validate/"
  validate_set_volume: 200
  validate_batch_size: 100

gpu_id: 0

high_cut: 10000
noise: 0.001
tag: 'einf_n001'


iter_head: 0
epochs: 1000

lr: 0.001
weight_decay: 0.000000001
momentum: 0.9

log_dir: "./test_multi/u100_/logs/"
save: True
checkpoint_dir: "./test_multi/u100_/checkpoints/"
