
data:
  train_set_location: "./data/gdgn_64_64_train/"
  train_set_volume: 10000
  train_batch_size: 500
  validate_set_location: "./data/gdgn_64_64_validate/"
  validate_set_volume: 200
  validate_batch_size: 200

gpu_id: 0

noise: 0.01
use_noise_filter: False
tag: 'gn01_en'
type_: ''

iter_head: 0
epochs: 1500

lr: 0.001
weight_decay: 0.000000001
momentum: 0.9

log_dir: "./test_en/logs_g/"
save: True
checkpoint_dir: "./test_en/checkpoints/"
