workspace:
  ckpts_folder: 'ckpts'
  logs_folder: 'logs'
  epoch_prefix: 'e'
  ckpts_extension: '.pt'
  step_key: 'step'


final:
  data.gd_folder: data/cir3_64x64_c8_s26710/gd
  data.inclusion_folder: data/cir3_64x64_c8_s26710/inclusion
  data.train_set_start: 0
  data.train_set_end: 10000
  data.valid_set_start: 10000
  data.valid_set_end: 12000

  model.input_dims: 2016 # = 252 * 8
  model.hidden_dims: [150, 150, 150, 150]
  model.output_dims: 4096
  model.activation: leaky_relu

  optim.lr: 1.0
  optim.weight_decay: 0.0000001

  train.epochs: 15000
  train.batch_size: 1000
  train.loss_func: bce
