
data:
  train_set_location: "./data/cir3_e64_64_c8/"
  train_set_start: 0
  train_set_end: 10000
  train_batch_size: 500

  validate_set_location: "./data/cir3_e64_64_c8"
  validate_set_start: 10000
  validate_set_end: 12000
  validate_batch_size: 500


gpu_id: 0


noise: 0.01
use_noise_filter: False
tag: 'gn01_multi'
type_: ''


iter_head: 0
epochs: 1500


lr: 0.001
weight_decay: 0.000000001
momentum: 0.9


log_dir: "./test_fem_version/logs_g/"
save: False
checkpoint_dir: "./test_fem_version/ckpts/"
